/**
 * Lightweight, explicit request-path allowlist for the production trailing-
 * slash policy. Keep this module dependency-free: `src/proxy.ts` is deployed
 * on the request path and must not pull the multi-megabyte production SEO
 * evidence fixture into the proxy bundle.
 *
 * Unknown paths are deliberately absent. They must fall through to the
 * application 404 instead of becoming accidental wildcard aliases.
 */
export const EXPLICIT_TRAILING_SLASH_PATHS = [
  '/about-us',
  '/blog',
  '/blog/category/custom-epoxy-stickers',
  '/blog/category/custom-foil-stickers',
  '/blog/category/custom-holographic-stickers',
  '/blog/category/custom-jute-tote-bags',
  '/blog/category/custom-mylar-bags',
  '/blog/category/custom-puffy-stickers',
  '/blog/category/sticker-psychology',
  '/blog/custom-jute-tote-bags-the-perfect-blend-of-sustainability',
  '/blog/custom-puffy-stickers-became-the-new-therapy',
  '/blog/custom-puffy-stickers-guide',
  '/blog/why-custom-stickers-feel-like-objects',
  '/blog/holographic-stickers-color-perception',
  '/blog/matte-vs-gloss-psychology',
  '/blog/page/2',
  '/blog/puffy-stickers-are-trending-2025',
  '/blog/soft-depth-vs-smooth-depth',
  '/blog/sound-of-packaging-mylar-bags',
  '/blog/tag/3d-holographic',
  '/blog/tag/childhood-keepsakes',
  '/blog/tag/collectible-stickers',
  '/blog/tag/collecting-psychology',
  '/blog/tag/custom-epoxy-stickers',
  '/blog/tag/custom-foil-stickers',
  '/blog/tag/custom-jute-tote-bags',
  '/blog/tag/custom-mylar-bag',
  '/blog/tag/custom-puffy-sheets',
  '/blog/tag/custom-puffy-stickers',
  '/blog/tag/custom-stickers',
  '/blog/tag/dimensional-stickers',
  '/blog/tag/embossed-stickers',
  '/blog/tag/foil-stickers',
  '/blog/tag/foil-stickers-printing',
  '/blog/tag/holographic-materials',
  '/blog/tag/holographic-stickers',
  '/blog/tag/journaling',
  '/blog/tag/matte-vs-gloss',
  '/blog/tag/memory-and-collecting',
  '/blog/tag/mylar-bag',
  '/blog/tag/mylar-packaging',
  '/blog/tag/mylar-pouch',
  '/blog/tag/nostalgia',
  '/blog/tag/packaging-psychology',
  '/blog/tag/personal-archives',
  '/blog/tag/product-design',
  '/blog/tag/puffy-sheets',
  '/blog/tag/puffy-stickers',
  '/blog/tag/raised-stickers',
  '/blog/tag/soft-touch-mylar',
  '/blog/tag/soft-touch-packaging',
  '/blog/tag/sticker-books',
  '/blog/tag/sticker-nostalgia',
  '/blog/tag/sticker-psychology',
  '/blog/tag/stickers-psychology',
  '/blog/tag/texture-psychology',
  '/blog/tag/tote-bags',
  '/blog/tag/vintage-sticker-collecting',
  '/blog/tag/why-we-keep-stickers',
  '/blog/when-3d-stickers-become-collectibles',
  '/blog/why-foil-stickers-feel-valuable',
  '/blog/why-sticker-books-never-really-disappeared',
  '/blog/why-we-save-stickers-we-never-use',
  '/contact-us',
  '/faqs',
  '/flat-labels-stickers',
  '/flat-labels-stickers/bottle-labels',
  '/flat-labels-stickers/bumper-stickers',
  '/flat-labels-stickers/cheap-stickers',
  '/flat-labels-stickers/clear-vinyl-labels',
  '/flat-labels-stickers/custom-stickers',
  '/flat-labels-stickers/holographic-stickers',
  '/flat-labels-stickers/metallic-foil-stickers',
  '/privacy-policy',
  '/product/3d-labels',
  '/product/bottle-labels',
  '/product/bumper-stickers',
  '/product/cheap-stickers',
  '/product/clear-vinyl-labels',
  '/product/custom-stickers',
  '/product/dome-decals',
  '/product/eco-friendly-kraft-mylar-bags',
  '/product/epoxy-stickers',
  '/product/foam-stickers',
  '/product/holographic-stickers',
  '/product/jute-bag',
  '/product/metallic-foil-stickers',
  '/product/non-woven-bag',
  '/product/nylon-bag',
  '/product/paper-bag',
  '/product/pu-embossed-stickers',
  '/product/puffy-stickers',
  '/product/puffy-sticker-sheets',
  '/product/washable-paper-bags',
  '/product/woven-bags',
  '/product-category/flat-labels-stickers',
  '/product-category/promotional-items',
  '/product-category/puffy-labels-stickers',
  '/product-tag/embossed-stickers',
  '/product-tag/pu-labels',
  '/promotional-items',
  '/promotional-items/eco-friendly-kraft-mylar-bags',
  '/promotional-items/jute-bag',
  '/promotional-items/non-woven-bag',
  '/promotional-items/nylon-bag',
  '/promotional-items/paper-bag',
  '/promotional-items/washable-paper-bags',
  '/promotional-items/woven-bags',
  '/puff-labels-stickers/3d-labels',
  '/puff-labels-stickers/dome-decals',
  '/puff-labels-stickers/epoxy-stickers',
  '/puff-labels-stickers/foam-stickers',
  '/puff-labels-stickers/pu-embossed-stickers',
  '/puff-labels-stickers/puffy-stickers',
  '/puff-labels-stickers/puffy-sticker-sheets',
  '/puffy-labels-stickers',
  '/puffy-labels-stickers/3d-labels',
  '/puffy-labels-stickers/dome-decals',
  '/puffy-labels-stickers/epoxy-stickers',
  '/puffy-labels-stickers/foam-stickers',
  '/puffy-labels-stickers/pu-embossed-stickers',
  '/puffy-labels-stickers/puffy-stickers',
  '/puffy-labels-stickers/puffy-sticker-sheets',
  '/reprint-policy',
  '/request-a-quote',
  '/resources',
  '/shipping-delivery',
  '/shop',
  '/terms-of-service',
] as const

export const EXPLICIT_TRAILING_SLASH_PATH_SET: ReadonlySet<string> = new Set(
  EXPLICIT_TRAILING_SLASH_PATHS,
)

/** Exact query-sensitive target reached by the preserved `/shop/` canonical. */
export const SHOP_CANONICAL_QUERY_REDIRECT = {
  pathname: '/',
  search: '?page_id=9',
  destination: '/puffy-labels-stickers/puffy-stickers/',
  status: 301,
} as const
