const body = `<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="//puffsticker.com/main-sitemap.xsl"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
\t<sitemap>
\t\t<loc>https://puffsticker.com/post-sitemap.xml</loc>
\t\t<lastmod>2026-08-31T22:19:46+00:00</lastmod>
\t</sitemap>
\t<sitemap>
\t\t<loc>https://puffsticker.com/page-sitemap.xml</loc>
\t\t<lastmod>2026-07-13T20:21:40+00:00</lastmod>
\t</sitemap>
\t<sitemap>
\t\t<loc>https://puffsticker.com/product-sitemap.xml</loc>
\t\t<lastmod>2026-08-07T08:05:48+00:00</lastmod>
\t</sitemap>
\t<sitemap>
\t\t<loc>https://puffsticker.com/product_cat-sitemap.xml</loc>
\t\t<lastmod>2026-08-07T08:05:48+00:00</lastmod>
\t</sitemap>
\t<sitemap>
\t\t<loc>https://puffsticker.com/local-sitemap.xml</loc>
\t\t<lastmod>2026-04-12T23:24:59+00:00</lastmod>
\t</sitemap>
</sitemapindex>
<!-- XML Sitemap generated by Rank Math SEO Plugin (c) Rank Math - rankmath.com -->`

export const productionSitemapIndexCurrentDeltaFixture = {
  source: 'production-http-capture-2026-09-02',
  capturedOn: '2026-09-02',
  endpoint: {
    requestedUrl: 'https://puffsticker.com/sitemap_index.xml',
    finalUrl: 'https://puffsticker.com/sitemap_index.xml',
    status: 200,
    contentType: 'text/xml; charset=UTF-8',
    normalizedBodyHash: 'c271fcd14d40736e0b9abf747e9b9c2e06d74adc512f8e2558fb7bcbc28a56d7',
    body,
  },
} as const

export default productionSitemapIndexCurrentDeltaFixture
