export type CategorySlug = 'puffy-labels-stickers' | 'flat-labels-stickers' | 'promotional-items' | 'cbd-packaging-boxes'

export type CatalogProduct = {
  id: number
  slug: string
  name: string
  category: CategorySlug
  eyebrow: string
  tagline: string
  summary: string
  overview: string
  price: string
  image: string
  sourceUrl: string
  accent: string
  accentSoft: string
  features: Array<{ title: string; text: string }>
  specifications: Array<{ label: string; value: string }>
  applications: string[]
  options: string[]
}

export const categories: Record<
  CategorySlug,
  {
    name: string
    shortName: string
    kicker: string
    description: string
    href: string
    accent: string
    image: string
  }
> = {
  'puffy-labels-stickers': {
    name: 'Puffy Labels & Stickers',
    shortName: 'Puffy & 3D',
    kicker: 'Tactile dimension',
    description: 'Raised, dimensional labels engineered to make packaging, merchandise and brand touchpoints feel as distinctive as they look.',
    href: '/puffy-labels-stickers',
    accent: '#f4bd34',
    image: '/assets/puffy-monster.webp',
  },
  'flat-labels-stickers': {
    name: 'Flat Labels & Stickers',
    shortName: 'Flat Labels',
    kicker: 'Versatile brand systems',
    description: 'Custom-cut labels and decals across clear, matte, gloss, holographic and metallic finishes for everyday brand application.',
    href: '/flat-labels-stickers',
    accent: '#79cce8',
    image: '/assets/catalog/holographic-stickers.webp',
  },
  'promotional-items': {
    name: 'Promotional Items',
    shortName: 'Bags & Packaging',
    kicker: 'Brand beyond the label',
    description: 'Custom bags and pouches made for retail, events, food, gifting and repeat brand visibility.',
    href: '/promotional-items',
    accent: '#8be2d7',
    image: '/assets/catalog/woven-bags.webp',
  },
  'cbd-packaging-boxes': {
    name: 'CBD Packaging Boxes',
    shortName: 'CBD Packaging',
    kicker: 'Retail-ready packaging',
    description: 'Custom CBD and hemp boxes built around the product, compliance panel, closure and shelf presentation.',
    href: '/cbd-packaging-boxes',
    accent: '#d6a957',
    image: '/assets/catalog/mylar-bags.webp',
  },
}

const legacyCatalogProducts: CatalogProduct[] = [
  {
    id: 17645,
    slug: 'puffy-stickers',
    name: 'Puffy Stickers',
    category: 'puffy-labels-stickers',
    eyebrow: 'The signature soft feel',
    tagline: 'Soft dimension that makes a brand impossible to ignore.',
    summary: 'Custom die-cut stickers with a soft 1 mm foam core, printed vinyl face and tactile raised finish.',
    overview: 'Puffy stickers combine a soft foam center with printed vinyl, a durable adhesive and a protective gloss or matte surface. Each order is cut to the artwork outline and digitally proofed before production.',
    price: 'From $1.85',
    image: '/assets/catalog/puffy-stickers.webp',
    sourceUrl: 'https://puffsticker.com/puffy-labels-stickers/puffy-stickers/',
    accent: '#f6c33e',
    accentSoft: '#fff2be',
    features: [
      { title: 'Signature 1 mm raise', text: 'A soft foam center creates the dimensional, squeezable feel.' },
      { title: 'Protected color', text: 'A clear laminate helps resist scratches and fading.' },
      { title: 'Proof before production', text: 'Your custom shape and artwork are reviewed before the run starts.' },
    ],
    specifications: [
      { label: 'Construction', value: 'Printed vinyl + soft foam + adhesive' },
      { label: 'Size range', value: '0.5–4 inches' },
      { label: 'Finish', value: 'Gloss or matte' },
      { label: 'Minimum order', value: 'Confirmed with your quote' },
    ],
    applications: ['Brand promotions', 'Product packaging', 'Merchandise', 'Gifts & collections'],
    options: ['Custom shape', 'Custom size', 'Unlimited color', 'Digital proof'],
  },
  {
    id: 17641,
    slug: 'puffy-sticker-sheets',
    name: 'Puffy Sticker Sheets',
    category: 'puffy-labels-stickers',
    eyebrow: 'Multiple designs, one sheet',
    tagline: 'A full tactile collection, ready to peel.',
    summary: 'Custom sheets with soft raised stickers, vibrant printing and room for up to 40 individual designs.',
    overview: 'Puffy sticker sheets bring multiple custom designs together on a single easy-to-use sheet. The raised foam texture, precision die cutting and gloss or matte surface make them a playful format for merchandise, campaigns and creative projects.',
    price: 'From $3.00',
    image: '/assets/catalog/puffy-sticker-sheets.webp',
    sourceUrl: 'https://puffsticker.com/puffy-labels-stickers/puffy-sticker-sheets/',
    accent: '#ad86d7',
    accentSoft: '#eadcf8',
    features: [
      { title: 'Up to 40 stickers', text: 'Build a varied collection on a single custom sheet.' },
      { title: 'Soft 3D texture', text: 'Every piece carries the tactile puffy construction.' },
      { title: 'Bulk friendly', text: 'A practical format for giveaways and custom merchandise.' },
    ],
    specifications: [
      { label: 'Format', value: 'Multi-design sticker sheet' },
      { label: 'Capacity', value: 'Up to 40 stickers per sheet' },
      { label: 'Finish', value: 'Gloss or matte' },
      { label: 'Listed quantities', value: '1,000 / 2,000 / 5,000' },
    ],
    applications: ['Giveaways', 'Merchandise', 'Journals', 'Laptops & phone cases'],
    options: ['Multiple designs', 'Custom sheet size', 'Smooth finish', 'Matte finish'],
  },
  {
    id: 17652,
    slug: '3d-labels',
    name: '3D Labels',
    category: 'puffy-labels-stickers',
    eyebrow: 'Built in layers',
    tagline: 'Structured depth for packaging with presence.',
    summary: 'Three-layer labels pairing adhesive, printed vinyl and a UV or resin-coated top surface.',
    overview: '3D labels are lightweight, damage-resistant and fully customizable. Their layered construction can be made soft and puffy or firm and structured, with a smooth glossy or matte surface.',
    price: 'From $2.00',
    image: '/assets/catalog/3d-labels.webp',
    sourceUrl: 'https://puffsticker.com/puffy-labels-stickers/3d-labels/',
    accent: '#78ded5',
    accentSoft: '#d8f6f2',
    features: [
      { title: 'Three-layer build', text: 'Adhesive, vinyl and a protective top coat work together.' },
      { title: 'Soft or structured', text: 'Choose a foam-filled feel or a firmer dimensional finish.' },
      { title: 'Precision custom form', text: 'Shapes, colors and sizes follow your brand artwork.' },
    ],
    specifications: [
      { label: 'Construction', value: 'Adhesive + vinyl + UV/resin top' },
      { label: 'Surface', value: 'Soft puffy or firm structured' },
      { label: 'Finish', value: 'Gloss or matte' },
      { label: 'Format', value: 'Custom shape and size' },
    ],
    applications: ['Product packaging', 'Branding', 'Promotional pieces', 'Crafting & journals'],
    options: ['Soft foam fill by request', 'Firm top by request', 'Gloss', 'Matte'],
  },
  {
    id: 17651,
    slug: 'dome-decals',
    name: 'Dome Decals',
    category: 'puffy-labels-stickers',
    eyebrow: 'Rigid, polished depth',
    tagline: 'A clear resin dome with professional shine.',
    summary: 'Printed vinyl labels capped with a clear rounded resin surface for gloss, protection and dimensional impact.',
    overview: 'Dome decals use a clear polyurethane-style resin over printed vinyl to create a smooth, rounded and durable surface. They are a strong fit for logos, equipment branding and promotional giveaways.',
    price: 'From $2.00',
    image: '/assets/catalog/dome-decals.webp',
    sourceUrl: 'https://puffsticker.com/puffy-labels-stickers/dome-decals/',
    accent: '#fa8ca6',
    accentSoft: '#ffe0e8',
    features: [
      { title: 'High-gloss dome', text: 'Clear resin magnifies color and gives the label a rounded profile.' },
      { title: 'Built for handling', text: 'The rigid surface adds durable protection to printed artwork.' },
      { title: 'Professional finish', text: 'A clean, premium option for product and equipment branding.' },
    ],
    specifications: [
      { label: 'Construction', value: 'Clear resin over printed vinyl' },
      { label: 'Surface', value: 'Rigid, raised and glossy' },
      { label: 'Shapes', value: 'Circle, oval, square or custom' },
      { label: 'Use', value: 'Indoor and outdoor branding' },
    ],
    applications: ['Logos', 'Equipment badges', 'Packaging', 'Promotional giveaways'],
    options: ['Custom shape', 'Custom size', 'Full color', 'Clear dome'],
  },
  {
    id: 17650,
    slug: 'epoxy-stickers',
    name: 'Epoxy Stickers',
    category: 'puffy-labels-stickers',
    eyebrow: 'Glass-like depth',
    tagline: 'A sleek raised surface with flexible polish.',
    summary: 'Printed adhesive vinyl with a clear raised resin coating for a smooth, glossy and dimensional appearance.',
    overview: 'Epoxy stickers add a clear, glass-like resin coating over printed artwork. The finished label is raised and delivered on easy-peel sheets in custom shapes and sizes.',
    price: 'From $2.10',
    image: '/assets/catalog/epoxy-stickers.webp',
    sourceUrl: 'https://puffsticker.com/puffy-labels-stickers/epoxy-stickers/',
    accent: '#39bed8',
    accentSoft: '#d7f4f8',
    features: [
      { title: 'Glass-like surface', text: 'A clear resin coating increases visual depth and protects the artwork.' },
      { title: 'Raised profile', text: 'The resin layer gives printed artwork a dimensional finish.' },
      { title: 'Easy-peel format', text: 'Supplied on sheets for efficient brand application.' },
    ],
    specifications: [
      { label: 'Construction', value: 'Clear resin over adhesive vinyl' },
      { label: 'Surface', value: 'Clear and raised' },
      { label: 'Finish', value: 'Gloss or matte' },
      { label: 'Format', value: 'Easy-peel sheets' },
    ],
    applications: ['Premium packaging', 'Brand labels', 'Promotional items', 'Product presentation'],
    options: ['Custom shape', 'Multiple sizes', 'Gloss', 'Matte'],
  },
  {
    id: 17649,
    slug: 'foam-stickers',
    name: 'Foam Stickers',
    category: 'puffy-labels-stickers',
    eyebrow: 'Soft and flexible',
    tagline: 'Playful dimension with a durable EVA build.',
    summary: 'Premium EVA foam labels with strong adhesive and thickness options from 0.5 to 2 mm.',
    overview: 'Foam stickers keep their shape while staying soft and flexible. Their EVA construction and strong adhesive make them useful for packaging, gifts and creative brand applications.',
    price: 'From $2.10',
    image: '/assets/catalog/foam-stickers.webp',
    sourceUrl: 'https://puffsticker.com/puffy-labels-stickers/foam-stickers/',
    accent: '#ffd4c8',
    accentSoft: '#fff0eb',
    features: [
      { title: 'Premium EVA', text: 'A soft, flexible material that retains its form.' },
      { title: 'Variable thickness', text: 'Choose a profile from 0.5 to 2 mm.' },
      { title: 'Strong adhesive', text: 'Made to stay securely in place through regular handling.' },
    ],
    specifications: [
      { label: 'Material', value: 'EVA foam' },
      { label: 'Thickness', value: '0.5–2 mm' },
      { label: 'Finish', value: 'Gloss or matte' },
      { label: 'Cut', value: 'Custom shape and size' },
    ],
    applications: ['Packaging accents', 'Personalized gifts', 'Craft projects', 'Brand badges'],
    options: ['Multiple thicknesses', 'Custom shape', 'Gloss', 'Matte'],
  },
  {
    id: 18935,
    slug: 'pu-embossed-stickers',
    name: 'PU Embossed Stickers',
    category: 'puffy-labels-stickers',
    eyebrow: 'Material depth',
    tagline: 'Leather-like texture with selectively raised detail.',
    summary: 'Soft-touch PU labels with a matte grain, multilayer build and precise convex embossing.',
    overview: 'PU embossed stickers are designed for a refined, non-reflective finish. The soft leather-like grain and structured elevation bring subtle dimension to logos on fashion, technology and luxury packaging.',
    price: 'From $3.00',
    image: '/assets/catalog/pu-embossed.webp',
    sourceUrl: 'https://puffsticker.com/puffy-labels-stickers/pu-embossed-stickers/',
    accent: '#b68762',
    accentSoft: '#ead9cb',
    features: [
      { title: 'Leather-like grain', text: 'A premium matte surface with a soft tactile finish.' },
      { title: 'Selective elevation', text: 'Convex details highlight the most important parts of a mark.' },
      { title: 'Structured durability', text: 'A multilayer build resists scratches and light moisture.' },
    ],
    specifications: [
      { label: 'Material', value: 'Soft-touch PU' },
      { label: 'Surface', value: 'Matte leather-like grain' },
      { label: 'Effect', value: 'Selective convex embossing' },
      { label: 'Adhesion', value: 'Permanent adhesive' },
    ],
    applications: ['Fashion apparel', 'Tech accessories', 'Luxury packaging', 'Premium brand marks'],
    options: ['Custom embossing', 'Custom shape', 'Matte grain', 'Multilayer build'],
  },
  {
    id: 17695,
    slug: 'custom-stickers',
    name: 'Custom Stickers',
    category: 'flat-labels-stickers',
    eyebrow: 'Your artwork, made tangible',
    tagline: 'A flexible vinyl format for everyday brand recognition.',
    summary: 'Full-color custom stickers in brand-specific shapes, sizes and colors with matte or glossy finishes.',
    overview: 'Custom stickers turn a logo, message or illustration into an easy-to-apply branding tool. Artwork can be produced in die-cut or standard shapes on durable vinyl sheets with easy-peel backing.',
    price: 'From $1.85',
    image: '/assets/catalog/custom-stickers.webp',
    sourceUrl: 'https://puffsticker.com/flat-labels-stickers/custom-stickers/',
    accent: '#f4bd34',
    accentSoft: '#fff2be',
    features: [
      { title: 'Fully custom', text: 'Match brand colors, scale and the exact shape of your artwork.' },
      { title: 'Matte or gloss', text: 'Choose a smooth low-glare finish or brighter reflective color.' },
      { title: 'Artwork support', text: 'The team can review sizing, cut lines and print readiness.' },
    ],
    specifications: [
      { label: 'Material', value: 'Printed adhesive vinyl' },
      { label: 'Cut', value: 'Die-cut or standard shape' },
      { label: 'Finish', value: 'Matte or gloss' },
      { label: 'Minimum order', value: 'Confirmed with your quote' },
    ],
    applications: ['Packaging', 'Giveaways', 'Events', 'Cards & gifts'],
    options: ['Custom shape', 'Custom size', 'Full color', 'Matte or gloss'],
  },
  {
    id: 17696,
    slug: 'clear-vinyl-labels',
    name: 'Clear Vinyl Labels',
    category: 'flat-labels-stickers',
    eyebrow: 'Seamless branding',
    tagline: 'Let the product show through the label.',
    summary: 'Transparent vinyl labels printed in black, white or full color for a clean, integrated look.',
    overview: 'Clear vinyl labels blend into bottles, jars and packaging while keeping the artwork crisp. Each label can be customized by shape and size, with artwork reviewed before ordering.',
    price: 'From $1.70',
    image: '/assets/catalog/clear-vinyl.webp',
    sourceUrl: 'https://puffsticker.com/flat-labels-stickers/clear-vinyl-labels/',
    accent: '#f198bb',
    accentSoft: '#fae2ec',
    features: [
      { title: 'Transparent base', text: 'Branding appears directly on the product surface.' },
      { title: 'Flexible print choices', text: 'Use black, white or full-color artwork.' },
      { title: 'Clean presentation', text: 'A strong choice for minimal, product-led packaging.' },
    ],
    specifications: [
      { label: 'Material', value: 'Clear adhesive vinyl' },
      { label: 'Print', value: 'Black, white or full color' },
      { label: 'Shape', value: 'Custom sizes and contours' },
      { label: 'Preview', value: 'Artwork preview before ordering' },
    ],
    applications: ['Bottles', 'Jars', 'Cosmetics', 'Minimal packaging'],
    options: ['Black print', 'White print', 'Full color', 'Custom cut'],
  },
  {
    id: 17699,
    slug: 'bottle-labels',
    name: 'Bottle Labels',
    category: 'flat-labels-stickers',
    eyebrow: 'Packaging precision',
    tagline: 'Labels designed around the bottle and the brand.',
    summary: 'Custom bottle labels across white vinyl, transparent film, holographic and foil materials.',
    overview: 'Bottle labels are produced in shapes ranging from clean ovals to detailed custom frames. Durable, water-resistant material options support beverages, cosmetics, favors and specialty products.',
    price: 'From $1.98',
    image: '/assets/catalog/bottle-labels.webp',
    sourceUrl: 'https://puffsticker.com/flat-labels-stickers/bottle-labels/',
    accent: '#91b8ec',
    accentSoft: '#e3edfb',
    features: [
      { title: 'Format flexibility', text: 'Build around the bottle with classic or custom shapes.' },
      { title: 'Multiple materials', text: 'Choose white vinyl, clear film, holographic or foil.' },
      { title: 'Water-resistant options', text: 'Designed for products that meet moisture and handling.' },
    ],
    specifications: [
      { label: 'Materials', value: 'White vinyl, clear, holographic or foil' },
      { label: 'Shape', value: 'Oval, framed or custom' },
      { label: 'Print', value: 'Custom brand artwork' },
      { label: 'Use', value: 'Bottle and flask labeling' },
    ],
    applications: ['Beverages', 'Cosmetics', 'Event favors', 'Specialty products'],
    options: ['White vinyl', 'Transparent film', 'Holographic', 'Foil'],
  },
  {
    id: 17606,
    slug: 'holographic-stickers',
    name: 'Holographic Stickers',
    category: 'flat-labels-stickers',
    eyebrow: 'Light in motion',
    tagline: 'A rainbow shift that changes with every angle.',
    summary: 'Decorative holographic vinyl with a reflective, color-shifting surface for visual impact.',
    overview: 'Holographic stickers enhance artwork with a smooth rainbow shift across the material. They can be supplied as individual die-cut pieces or in sheets with multiple designs.',
    price: 'From $4.00',
    image: '/assets/catalog/holographic-stickers.webp',
    sourceUrl: 'https://puffsticker.com/flat-labels-stickers/holographic-stickers/',
    accent: '#847cf0',
    accentSoft: '#e6e3ff',
    features: [
      { title: 'Color-shifting surface', text: 'The finish changes with light and movement.' },
      { title: 'Custom formats', text: 'Choose individual stickers or a multi-design sheet.' },
      { title: 'Decorative impact', text: 'Made for branding and visual use, not security authentication.' },
    ],
    specifications: [
      { label: 'Material', value: 'Decorative holographic vinyl' },
      { label: 'Cut', value: 'Die-cut or kiss-cut' },
      { label: 'Format', value: 'Individual or sheet' },
      { label: 'Purpose', value: 'Decorative and branding use' },
    ],
    applications: ['Limited editions', 'Tech products', 'Retail packaging', 'Event merchandise'],
    options: ['Custom shape', 'Multiple designs', 'Individual cut', 'Sheet format'],
  },
  {
    id: 17684,
    slug: 'metallic-foil-stickers',
    name: 'Metallic Foil Stickers',
    category: 'flat-labels-stickers',
    eyebrow: 'A luxury signal',
    tagline: 'Metallic detail that elevates packaging instantly.',
    summary: 'Adhesive-backed clear vinyl printed with rose gold, silver or gold metallic finishes.',
    overview: 'Metallic foil stickers bring shine and detail to premium labeling. The clear vinyl base keeps the presentation clean while metallic print highlights the brand mark.',
    price: 'From $4.00',
    image: '/assets/catalog/metallic-foil.webp',
    sourceUrl: 'https://puffsticker.com/flat-labels-stickers/metallic-foil-stickers/',
    accent: '#bd7c43',
    accentSoft: '#f0dfcf',
    features: [
      { title: 'True metallic presence', text: 'Reflective foil catches the light with premium contrast.' },
      { title: 'Three classic tones', text: 'Select rose gold, silver or gold.' },
      { title: 'Clear vinyl base', text: 'Keeps attention on the metallic artwork.' },
    ],
    specifications: [
      { label: 'Material', value: 'Adhesive-backed clear vinyl' },
      { label: 'Foils', value: 'Rose gold, silver or gold' },
      { label: 'Print', value: 'Custom metallic artwork' },
      { label: 'Use', value: 'Premium labels and packaging' },
    ],
    applications: ['Luxury packaging', 'Premium labels', 'Event seals', 'Brand accents'],
    options: ['Rose gold', 'Silver', 'Gold', 'Custom contour'],
  },
  {
    id: 17698,
    slug: 'bumper-stickers',
    name: 'Bumper Stickers',
    category: 'flat-labels-stickers',
    eyebrow: 'Messages in motion',
    tagline: 'Thick vehicle decals made for the elements.',
    summary: 'Custom weather-resistant stickers designed for cars, trucks and other outdoor surfaces.',
    overview: 'Bumper stickers use thick, durable material intended to handle sun, wind and rain while keeping custom messages visible on the move.',
    price: 'From $1.70',
    image: '/assets/catalog/bumper-stickers.webp',
    sourceUrl: 'https://puffsticker.com/flat-labels-stickers/bumper-stickers/',
    accent: '#72b6dc',
    accentSoft: '#dceffa',
    features: [
      { title: 'Weather-resistant build', text: 'Designed for outdoor exposure and changing conditions.' },
      { title: 'Thick material', text: 'A durable decal format for vehicles and hard surfaces.' },
      { title: 'Fully custom message', text: 'Use brand artwork, safety information or campaign graphics.' },
    ],
    specifications: [
      { label: 'Material', value: 'Thick weather-resistant sticker stock' },
      { label: 'Surface', value: 'Vehicle and outdoor use' },
      { label: 'Print', value: 'Custom color artwork' },
      { label: 'Cut', value: 'Custom format' },
    ],
    applications: ['Cars & trucks', 'Outdoor messaging', 'Campaigns', 'Safety information'],
    options: ['Custom size', 'Custom shape', 'Full color', 'Weather-resistant stock'],
  },
  {
    id: 17697,
    slug: 'cheap-stickers',
    name: 'Cheap Stickers',
    category: 'flat-labels-stickers',
    eyebrow: 'Value at volume',
    tagline: 'A practical sticker for high-quantity moments.',
    summary: 'Budget-friendly custom stickers on splash-resistant paper for bulk use and everyday distribution.',
    overview: 'Cheap stickers are an economical option for giveaways, classrooms, collections and events. They are printed on splash-resistant paper; fully water-resistant jobs should use a vinyl alternative.',
    price: 'From $1.60',
    image: '/assets/catalog/cheap-stickers.webp',
    sourceUrl: 'https://puffsticker.com/flat-labels-stickers/cheap-stickers/',
    accent: '#ee9d91',
    accentSoft: '#fae2de',
    features: [
      { title: 'Bulk-minded value', text: 'A cost-conscious choice for wide distribution.' },
      { title: 'Splash-resistant paper', text: 'Good for indoor, everyday use.' },
      { title: 'Custom or ready-made', text: 'Adapt the format for campaigns, events and rewards.' },
    ],
    specifications: [
      { label: 'Material', value: 'Splash-resistant paper' },
      { label: 'Best use', value: 'Indoor and short-term' },
      { label: 'Format', value: 'Custom or selected design' },
      { label: 'Ordering', value: 'Bulk friendly' },
    ],
    applications: ['Giveaways', 'Classrooms', 'Collectors', 'Events & parties'],
    options: ['Custom artwork', 'Bulk quantities', 'Multiple designs', 'Paper stock'],
  },
  {
    id: 17682,
    slug: 'eco-friendly-kraft-mylar-bags',
    name: 'Mylar Bags',
    category: 'promotional-items',
    eyebrow: 'Custom flexible packaging',
    tagline: 'Pouches configured around the product inside.',
    summary: 'Custom stand-up, flat or gusseted pouches with printing and functional closure options.',
    overview: 'Mylar and kraft-look pouches support product packaging with custom dimensions, artwork and features such as zippers, windows or coffee valves. Configurations may include recyclable mono-PE and certified compostable kraft laminates where local facilities accept them.',
    price: 'From $5.00',
    image: '/assets/catalog/mylar-bags.webp',
    sourceUrl: 'https://puffsticker.com/promotional-items/eco-friendly-kraft-mylar-bags/',
    accent: '#b99168',
    accentSoft: '#eadfce',
    features: [
      { title: 'Configured to the product', text: 'Choose stand-up, flat or gusseted construction.' },
      { title: 'Functional additions', text: 'Add windows, zippers or coffee valves where needed.' },
      { title: 'Material choices', text: 'Ask about recyclable or compostable laminate options.' },
    ],
    specifications: [
      { label: 'Formats', value: 'Stand-up, flat or gusseted' },
      { label: 'Features', value: 'Window, zipper or coffee valve' },
      { label: 'Materials', value: 'Mylar, mono-PE or kraft laminate options' },
      { label: 'Print', value: 'Custom brand artwork' },
    ],
    applications: ['Food & coffee', 'Retail products', 'Samples', 'Specialty packaging'],
    options: ['Stand-up pouch', 'Flat pouch', 'Gusseted format', 'Closures & windows'],
  },
  {
    id: 17683,
    slug: 'jute-bag',
    name: 'Jute Bag',
    category: 'promotional-items',
    eyebrow: 'Natural brand carry',
    tagline: 'A durable woven bag with a natural material story.',
    summary: 'Custom-printed bags woven from natural jute fibers in a range of sizes, shapes and handle styles.',
    overview: 'Jute bags use strong plant-based fibers woven into a high-capacity reusable carry format. Custom printing turns the natural surface into practical everyday brand visibility.',
    price: 'From $6.00',
    image: '/assets/catalog/jute-bag.webp',
    sourceUrl: 'https://puffsticker.com/promotional-items/jute-bag/',
    accent: '#b9854d',
    accentSoft: '#ead8c3',
    features: [
      { title: 'Natural woven fibers', text: 'A recognizable texture with a natural material character.' },
      { title: 'Strong and reusable', text: 'Made to carry everyday items at useful volume.' },
      { title: 'Custom printed', text: 'Add brand artwork across a practical promotional surface.' },
    ],
    specifications: [
      { label: 'Material', value: 'Natural woven jute' },
      { label: 'Format', value: 'Multiple sizes and shapes' },
      { label: 'Handles', value: 'Multiple handle options' },
      { label: 'Branding', value: 'Custom printing' },
    ],
    applications: ['Retail', 'Events', 'Gifting', 'Everyday brand carry'],
    options: ['Custom size', 'Handle options', 'Custom artwork', 'Natural finish'],
  },
  {
    id: 17664,
    slug: 'nylon-bag',
    name: 'Nylon Bag',
    category: 'promotional-items',
    eyebrow: 'Lightweight utility',
    tagline: 'Reusable carry with weather-resistant practicality.',
    summary: 'Lightweight custom nylon bags designed for repeat use and full-color branding.',
    overview: 'Nylon bags combine low weight with practical weather resistance. They can be customized with CMYK printing for events, retail and reusable promotional programs.',
    price: 'From $9.90',
    image: '/assets/catalog/nylon-bag.webp',
    sourceUrl: 'https://puffsticker.com/promotional-items/nylon-bag/',
    accent: '#5ea2df',
    accentSoft: '#dcebf8',
    features: [
      { title: 'Lightweight', text: 'Easy to distribute, carry and reuse.' },
      { title: 'Weather-resistant', text: 'A practical surface for daily use.' },
      { title: 'CMYK branding', text: 'Supports vivid, full-color custom print.' },
    ],
    specifications: [
      { label: 'Material', value: 'Nylon' },
      { label: 'Use', value: 'Reusable promotional carry' },
      { label: 'Print', value: 'Custom CMYK artwork' },
      { label: 'Listed price range', value: '$9.90–$49.90 across quantity options' },
    ],
    applications: ['Events', 'Retail', 'Promotions', 'Reusable carry'],
    options: ['Custom size', 'Full-color print', 'Multiple formats', 'Bulk ordering'],
  },
  {
    id: 17678,
    slug: 'non-woven-bag',
    name: 'Non-Woven Bag',
    category: 'promotional-items',
    eyebrow: 'Everyday reusable carry',
    tagline: 'A versatile bag for high-visibility distribution.',
    summary: 'Custom non-woven bags using rPP or rPET material options for retail, events and promotions.',
    overview: 'Non-woven bags offer a lightweight reusable format with a broad printable surface. Material options include recycled polypropylene and recycled PET for brand programs seeking an alternative to single-use packaging.',
    price: 'From $9.95',
    image: '/assets/catalog/non-woven-bag.webp',
    sourceUrl: 'https://puffsticker.com/promotional-items/non-woven-bag/',
    accent: '#e48e4d',
    accentSoft: '#f7e2d2',
    features: [
      { title: 'Reusable format', text: 'Designed to keep moving beyond a single event.' },
      { title: 'Recycled material options', text: 'Ask about rPP and rPET constructions.' },
      { title: 'Large branding area', text: 'Make campaign artwork visible at distance.' },
    ],
    specifications: [
      { label: 'Materials', value: 'rPP or rPET options' },
      { label: 'Format', value: 'Reusable non-woven bag' },
      { label: 'Branding', value: 'Custom print' },
      { label: 'Listed price range', value: '$9.95–$39.95 across quantity options' },
    ],
    applications: ['Trade shows', 'Retail', 'Community events', 'Campaign kits'],
    options: ['rPP material', 'rPET material', 'Custom size', 'Custom artwork'],
  },
  {
    id: 17653,
    slug: 'woven-bags',
    name: 'Woven Bags',
    category: 'promotional-items',
    eyebrow: 'Heavy-duty visibility',
    tagline: 'Structured strength with a wipe-clean brand surface.',
    summary: 'Tear-resistant woven laminated bags with glossy or matte finishes and custom printing.',
    overview: 'Woven bags are made by extruding and tightly weaving material described by the source as recyclable, then adding a protective laminate. Local recycling capability depends on available facilities.',
    price: 'From $14.95',
    image: '/assets/catalog/woven-bags.webp',
    sourceUrl: 'https://puffsticker.com/promotional-items/woven-bags/',
    accent: '#b88a5b',
    accentSoft: '#eadbc9',
    features: [
      { title: 'Tear-resistant build', text: 'Tight woven construction supports heavier loads.' },
      { title: 'Protective laminate', text: 'A wipe-clean outer layer shields the printed surface.' },
      { title: 'Gloss or matte', text: 'Match the finish to the brand presentation.' },
    ],
    specifications: [
      { label: 'Construction', value: 'Tightly woven material; local recycling varies' },
      { label: 'Surface', value: 'Laminated and wipe-clean' },
      { label: 'Finish', value: 'Gloss or matte' },
      { label: 'Listed price range', value: '$14.95–$119.95 across quantity options' },
    ],
    applications: ['Retail', 'Heavy carry', 'Events', 'Reusable packaging'],
    options: ['Gloss laminate', 'Matte laminate', 'Custom size', 'Custom print'],
  },
  {
    id: 17657,
    slug: 'washable-paper-bags',
    name: 'Washable Paper Bags',
    category: 'promotional-items',
    eyebrow: 'Paper, reengineered',
    tagline: 'A reusable paper look with reinforced performance.',
    summary: 'Cellulose-reinforced, water-resistant paper bags made for reuse and custom branding.',
    overview: 'Washable paper bags retain the tactile appearance of paper while adding cellulose reinforcement, a polymer coating and water resistance. They are intended for gentle hand care or wipe-clean reuse.',
    price: 'From $14.90',
    image: '/assets/catalog/washable-paper-bags.webp',
    sourceUrl: 'https://puffsticker.com/promotional-items/washable-paper-bags/',
    accent: '#c9a779',
    accentSoft: '#eee3d2',
    features: [
      { title: 'Cellulose reinforced', text: 'A stronger interpretation of the familiar paper surface.' },
      { title: 'Water-resistant', text: 'Built for reuse and more demanding handling.' },
      { title: 'Distinctive texture', text: 'Adds a tactile, natural-looking brand touchpoint.' },
    ],
    specifications: [
      { label: 'Material', value: 'Cellulose-reinforced paper' },
      { label: 'Performance', value: 'Water-resistant; gentle hand care' },
      { label: 'Branding', value: 'Custom print' },
      { label: 'Listed price range', value: '$14.90–$99.90 across quantity options' },
    ],
    applications: ['Lifestyle retail', 'Gifting', 'Packaging', 'Reusable storage'],
    options: ['Custom size', 'Custom print', 'Size options', 'Bulk ordering'],
  },
  {
    id: 17661,
    slug: 'paper-bag',
    name: 'Paper Bag',
    category: 'promotional-items',
    eyebrow: 'Classic retail packaging',
    tagline: 'Simple kraft carry, configured for the brand.',
    summary: 'Custom white or brown kraft paper bags with full-color or monochrome printing.',
    overview: 'Paper bags provide a familiar retail and gifting format with flexible artwork options. Select white or brown kraft and apply either full-color or monochrome branding.',
    price: 'From $19.95',
    image: '/assets/catalog/paper-bag.webp',
    sourceUrl: 'https://puffsticker.com/promotional-items/paper-bag/',
    accent: '#d6a957',
    accentSoft: '#f1e3c7',
    features: [
      { title: 'White or brown kraft', text: 'Choose the base that best matches the brand palette.' },
      { title: 'Flexible printing', text: 'Use full-color artwork or a focused monochrome mark.' },
      { title: 'Retail ready', text: 'A straightforward format for purchases, gifting and events.' },
    ],
    specifications: [
      { label: 'Material', value: 'White or brown kraft paper' },
      { label: 'Print', value: 'Full color or monochrome' },
      { label: 'Format', value: 'Custom bag specification' },
      { label: 'Listed price range', value: '$19.95–$24.95 across listed options' },
    ],
    applications: ['Retail', 'Gifting', 'Events', 'Takeaway packaging'],
    options: ['White kraft', 'Brown kraft', 'Full-color print', 'Monochrome print'],
  },
]

const cbdProductDefinitions = [
  ['cbd-bottle-boxes', 'CBD Bottle Boxes', 'Custom CBD bottle boxes sized for oil, tincture, or topical bottles. Sturdy construction, secure fit, full branding, and wholesale pricing available.'],
  ['cbd-display-boxes', 'CBD Display Boxes', 'Custom CBD display boxes built to organize and showcase your product line at retail counters. Sturdy construction, full branding, and wholesale pricing available.'],
  ['cbd-gummy-boxes', 'CBD Gummy Boxes', 'Custom CBD gummy boxes for wrapped or sealed gummies, with tamper-evident options and vibrant full-color printing.'],
  ['cbd-kraft-boxes', 'CBD Kraft Boxes', 'Custom CBD kraft boxes with a natural, recyclable finish, durable construction and full-color printing.'],
  ['cbd-oil-packaging', 'CBD Oil Packaging', 'Custom CBD oil packaging built around your bottle size, with durable materials and full branding.'],
  ['cbd-sleeve-tray-boxes', 'CBD Sleeve Tray Boxes', 'Custom CBD sleeve and tray boxes with a two-piece design for an elevated retail look.'],
  ['cbd-tincture-boxes', 'CBD Tincture Boxes', 'Custom CBD tincture boxes sized for dropper bottles, with sturdy stock, secure fit and full-color branding.'],
  ['child-resistant-boxes', 'Child-Resistant Boxes', 'Custom child-resistant locking box styles, printed with full branding and built from durable materials.'],
  ['custom-cbd-boxes', 'Custom CBD Boxes', 'Fully custom CBD boxes in any size, material or finish for a single SKU or a complete product line.'],
  ['custom-hemp-boxes', 'Custom Hemp Boxes', 'Custom hemp boxes for a wide range of hemp-derived products, with durable materials and full branding.'],
] as const

const cbdProducts: CatalogProduct[] = cbdProductDefinitions.map(([slug, name, summary], index) => ({
  id: 30001 + index,
  slug,
  name,
  category: 'cbd-packaging-boxes',
  eyebrow: 'Custom retail packaging',
  tagline: summary,
  summary,
  overview: summary,
  price: 'Quote for pricing',
  image: '/assets/catalog/mylar-bags.webp',
  sourceUrl: `https://puffsticker.com/cbd-packaging-boxes/${slug}/`,
  accent: '#d6a957',
  accentSoft: '#f1e3c7',
  features: [
    { title: 'Built to fit', text: 'Dimensions and structure are configured around the product and retail requirements.' },
    { title: 'Full brand control', text: 'Artwork, copy, finishes and compliance panels are reviewed before production.' },
    { title: 'Wholesale production', text: 'Made to order from 250 pieces with a free digital proof.' },
  ],
  specifications: [
    { label: 'Minimum order', value: '250 pieces' },
    { label: 'Proof', value: 'Free digital proof before production' },
    { label: 'Production & delivery', value: '18–20 business days from proof approval' },
    { label: 'Format', value: 'Custom size, stock, structure and finish' },
  ],
  applications: ['CBD retail', 'Hemp products', 'Tinctures and oils', 'Gummies and wellness'],
  options: ['Custom dimensions', 'Custom print', 'Premium finishes', 'Protective inserts'],
}))

export const catalogProducts: CatalogProduct[] = [...legacyCatalogProducts, ...cbdProducts]

export function getProduct(slug?: string) {
  return catalogProducts.find((product) => product.slug === slug)
}

export function getProductsByCategory(category: CategorySlug) {
  return catalogProducts.filter((product) => product.category === category)
}

export function formatProductCount(category?: CategorySlug) {
  const count = category ? getProductsByCategory(category).length : catalogProducts.length
  return `${String(count).padStart(2, '0')} product${count === 1 ? '' : 's'}`
}
